### ISSUE TITLE
Call stack exceeded and 403 Forbidden errors

### ISSUE THREAD

**Issue by X-yn** [JamesKyburz/youtube-audio-stream#117]
As stated in the below stackoverflow post:
https://stackoverflow.com/questions/56601119/stream-audio-from-youtube-to-an-html-audio-tag
I've been experiencing call stack errors until I downloaded the source code and updated the dependencies myself.

**Please update the ytdl-core version to 0.29.2!**

**Comment by JamesKyburz** [comment]
Released `v0.3.1` with dependency updates.
