### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by KBD2** [JamesKyburz/youtube-audio-stream#130]
I'm getting the "maximum call stack size exceeded" crash, and it seems to be caused by the dependency on ytdl-core v4.5.0 instead of the latest v4.9.1.

**Comment by clffrd** [comment]
i am getting the same issue, have you found a solution for this?

**Comment by KBD2** [comment]
I copied the relevant code from `index.js` and stopped using the module.

**Comment by JamesKyburz** [comment]
I have now automated npm publish when ytdl-core is updated (if the new ci test passes)

Fixed.
