### ISSUE TITLE
How i can use this?

### ISSUE THREAD

**Issue by matheuschimelli** [JamesKyburz/youtube-audio-stream#28]
How i can use this?

**Comment by JamesKyburz** [comment]
What are you having problems with? Example code can be found in the readme and test. First you will need ffmpeg installed.

**Comment by matheuschimelli** [comment]
I want run on a server. But i dont can run the test. I already try this,
but not was worked for me.

Em qui, 24 de dez de 2015 21:23, James Kyburz <notifications@github.com>
escreveu:

**Comment by JamesKyburz** [comment]
The most likely cause is ffmpeg.

In order to help I need to know more information.

What error are you getting?
What version of node and operating system? `node --version`
What version of ffmpeg have you installed? `ffmpeg list`

**Comment by matheuschimelli** [comment]
I have this error 
open http://localhost:3000 for demo of audio stream
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/ubuntu/workspace/youtube-audio-stream/test/server.html'
    at Error (native)

**Comment by JamesKyburz** [comment]
Have you run `npm install` and then `npm test` without any errors?

**Comment by matheuschimelli** [comment]
yes 
mrcmrc:~/workspace/youtube-audio-stream (master) $ npm test

> youtube-audio-stream@0.0.16 test /home/ubuntu/workspace/youtube-audio-stream
> cat ./test/video.js | node ./node_modules/indexhtmlify/index.js > ./test/server.html && node ./test/server.js

open http://localhost:3000 for demo of audio stream
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at /home/ubuntu/workspace/youtube-audio-stream/node_modules/fluent-ffmpeg/lib/processor.js:119:22
    at /home/ubuntu/workspace/youtube-audio-stream/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at /home/ubuntu/workspace/youtube-audio-stream/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/workspace/youtube-audio-stream/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:1204:30
    at /home/ubuntu/workspace/youtube-audio-stream/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /home/ubuntu/workspace/youtube-audio-stream/node_modules/fluent-ffmpeg/lib/utils.js:227:9
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
npm ERR! Test failed.  See above for more details.

**Comment by JamesKyburz** [comment]
It looks like `ffmpeg` isn't installed or isn't in your path.

**Comment by matheuschimelli** [comment]
<code>which ffmpeg</code> return's nothing

**Comment by JamesKyburz** [comment]
OK, so ffmpeg is somehow broken...

I have had luck with this script running on ubuntu

https://raw.githubusercontent.com/sameersbn/docker-ffmpeg/master/install.sh

**Comment by matheuschimelli** [comment]
thank you, this has worked for me.

**Comment by JamesKyburz** [comment]
Great
