### ISSUE TITLE
ffmpeg throws an error...

### ISSUE THREAD

**Issue by shrukeh** [JamesKyburz/youtube-audio-stream#42]
Hello,

I am encountering this error

> Error: ffmpeg exited with code 1: Output #0, mp3, to 'pipe:1':
Output file #0 does not contain any stream

I am not sure if it's just due to my use case or what..

(I am trying to take the stream and pipe it into a mumble input stream; playing yt audio over mumble)

**Comment by Sorch** [comment]
Still no fixes for this?

**Comment by JamesKyburz** [comment]
@shrukeh @Sorch most likely an ffmpeg installation issue.

Does it work for you if you clone the repo and run 
```
npm t
```

**Comment by JamesKyburz** [comment]
I don't know what OS you are running but an example of how to install ffmpeg on ubuntu can be found at https://github.com/JamesKyburz/soundify/blob/master/Dockerfile which uses this module.

**Comment by Sorch** [comment]
its working right now on Manjaro with FFMPEG 1.3.x

**Comment by JamesKyburz** [comment]
@shrukeh Is it working for you now?

**Comment by shrukeh** [comment]
Yes thank you :)

**Comment by JamesKyburz** [comment]
Great.
