### ISSUE TITLE
Progress Bar is not moving

### ISSUE THREAD

**Issue by LeoNero** [JamesKyburz/youtube-audio-stream#51]
Why I'm streaming and audio, the player's progress bar does not move. Why does this happen? And how to solve it?

**Comment by matheuschimelli** [comment]
@LeoNero i think that, how it is a stream, not is possible to move the progress bar.

**Comment by JamesKyburz** [comment]
For this to work we would have to support http 206 (partial content) and range requests.

AFAIK this is not possible when we don't know the mp3 byte size in advance.

What you could do is first pipe the audio to an mp3 file, then progress would work.

**Comment by JamesKyburz** [comment]
Closing as there is currently no range support. Pull requests with support for ranges would be welcome.
