### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING in Chrome

### ISSUE THREAD

**Issue by ghost** [JamesKyburz/youtube-audio-stream#68]
I'm getting a net::ERR_INCOMPLETE_CHUNKED_ENCODING error in Google Chrome after the first minute or two of streaming, the streaming stops and restarts. What could be the issue? I see someone else had the issue too (see other issues) but it's closed without a response.

**Comment by maximilienborne** [comment]
I have the same problem, any idea ?

**Comment by JamesKyburz** [comment]
Sorry haven't had time to look at this.

I did manage to find and issue whereby the ytdl pipe was closed prior to all the data being sent to http response.. Though this doesn't always happen.

Any more details, chrome version, example code and what youtube url would help.

**Comment by JamesKyburz** [comment]
Sorry haven't had time to look at this. Any help to fix this would be welcome.

**Comment by RanjithNair** [comment]
I have seen this happening more on desktop browsers as  compared to Mobile browsers. Anyone got a workaround for this?
