### ISSUE TITLE
Streamed tracks missing duration

### ISSUE THREAD

**Issue by jakemmarsh** [JamesKyburz/youtube-audio-stream#9]
When I stream tracks, they're missing any indicator of duration/length or content size. This results in audio files with no known duration, they're unseekable, and sometimes throw errors like `net::ERR_INCOMPLETE_CHUNKED_ENCODING` and stop playing halfway through. I'm not sure if this is an issue with this library, ytdl-core, or ffmpeg?

**Comment by ilikejames** [comment]
I know this is a closed issue, but it doesn't look implemented or that its even possible. Is that correct? Could seeking from the <audio> be ever made to work?
