### ISSUE TITLE
Node usage example

### ISSUE THREAD

**Issue by calebeby** [JamesKyburz/youtube-audio-stream#94]
How would this be used in Node? Can you add an example to the `README`?

Thanks!

**Comment by JamesKyburz** [comment]
Thanks for the PR. Did you get it working with the readme example / [test code](https://github.com/JamesKyburz/youtube-audio-stream/blob/master/test/server.js)

**Comment by calebeby** [comment]
Yeah the example worked. What I mean by a node example is to not have a web browser involved, i.e. running `node index.js` and then the audio starts playing, without having to go to a webpage.

**Comment by calebeby** [comment]
Sweet thanks. I was trying the same thing except without the lame decoder. That would be my problem.
