### ISSUE TITLE
`audioonly` option in ytdl

### ISSUE THREAD

**Issue by calebeby** [JamesKyburz/youtube-audio-stream#98]
Hi again,

It looks like `ytdl-core` has an `audioonly` option for `filter`. Is there a reason that this is not being used? If not, can the ffmpeg logic be removed?

I'd be happy to PR

Thanks!

**Comment by JamesKyburz** [comment]
Not all videos have audio only. So unfortunately we're stuck with ffmpeg.
From the ytdl-core readme - Typically 1080p or better video does not have
audio encoded with it. The audio must be downloaded separately and merged
via an appropriate encoding library. ffmpeg is the most widely used tool,
